/*
Copyright (c) 2012-2024 Carsten Burstedde, Donna Calhoun
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "fc2d_geoclaw_regions_default.h"

#include <fclaw_regions.h>
#include "fc2d_geoclaw_fort.h"

#include "fc2d_geoclaw_options.h"

#include <fclaw_clawpatch.h>
#include <fclaw_clawpatch_options.h>

#include <fclaw_options.h>
#include <fclaw_global.h>

#ifdef __cplusplus
extern "C"
{
#endif

#if 0
/* Fix syntax highlighting */
#endif    

void geoclaw_read_regions_data_default(fclaw_global_t *glob, 
                                       fclaw_region_t **regions,
                                       int *num_regions,
                                       int *dim)
{
    /* Idea is that we may only need to change this file when updating to newer
       geoclaw code */
/* Sample regions.data file */
/*
########################################################
### DO NOT EDIT THIS FILE:  GENERATED AUTOMATICALLY ####
### To modify data, edit  setrun.py                 ####
###    and then "make .data"                        ####
########################################################

2                    =: num_regions         
3  3 0.00000000000000e+00  1.00000000000000e+04  -8.50000000000000e+01  -7.20000000000000e+01  -3.80000000000000e+01  -2.50000000000000e+01  
3  3 8.00000000000000e+03  2.60000000000000e+04  -9.00000000000000e+01  -8.00000000000000e+01  -3.00000000000000e+01  -1.50000000000000e+01  

*/

    int max_line_len = 200;

    char line[max_line_len];
    FILE *f_regions_data = fopen("regions.data","r");

    /* Read header */
    for(int i = 0; i < 5; i++)
    {
        /* Read lines of each header file.  Assume 100 chars in each line */
        fgets(line, max_line_len, f_regions_data);
        if (line[0] != '#')
        {
            fclaw_global_essentialf("\n\n");
            fclaw_global_essentialf("read_regions_data : Error reading header.\n");
            exit(0);
        }
    }
    /* blank line */
    fgets(line,max_line_len, f_regions_data); 

    /* Read number of regions */
    fgets(line,max_line_len, f_regions_data);
    *num_regions = strtod(line,NULL);

    /* 
        In Geoclaw, the dim will always be 2, so we don't read
        it in from the regions.data file.
    */
    *dim = 2;

    if (*num_regions == 0)
    {
        *regions = NULL;
    }
    else
    {
        fclaw_regions_allocate(glob,*num_regions,regions);

        int *num = FCLAW_ALLOC(int,   *num_regions);
        double *xlower  = FCLAW_ALLOC(double,*num_regions);
        double *xupper  = FCLAW_ALLOC(double,*num_regions);
        double *ylower  = FCLAW_ALLOC(double,*num_regions);
        double *yupper  = FCLAW_ALLOC(double,*num_regions);
        double *t1  = FCLAW_ALLOC(double,*num_regions);
        double *t2  = FCLAW_ALLOC(double,*num_regions);
        int *min_level = FCLAW_ALLOC(int,*num_regions);
        int *max_level = FCLAW_ALLOC(int,*num_regions);

        /* Read region info */
        for(int i = 0; i < *num_regions; i++)
        {                        
            char *next;
            fgets(line,max_line_len, f_regions_data);
            num[i] = i; // Regions are not given IDs (unlike gauges)
            min_level[i] = strtod(line,&next);
            max_level[i] = strtod(next,&next);
            t1[i] = strtod(next,&next);
            t2[i] = strtod(next,&next);
            xlower[i] = strtod(next,&next);
            xupper[i] = strtod(next,&next);
            ylower[i] = strtod(next,&next);
            yupper[i] = strtod(next,NULL);
        }

        fclaw_region_t *r = regions[0];
        for(int i = 0; i < *num_regions; i++)
        {
            double zlower = 0;
            double zupper = 1;
            fclaw_region_set_data(glob,&r[i],num[i],*dim,
                                 xlower[i],xupper[i],
                                 ylower[i],yupper[i],
                                 zlower,zupper,
                                 min_level[i],max_level[i],
                                 t1[i],t2[i]);
        }

        FCLAW_FREE(num);
        FCLAW_FREE(xlower);
        FCLAW_FREE(xupper);
        FCLAW_FREE(ylower);
        FCLAW_FREE(yupper);
        FCLAW_FREE(t1);
        FCLAW_FREE(t2);
        FCLAW_FREE(min_level);
        FCLAW_FREE(max_level);

    }   /* End of num_regions > 0 loop */

    /* Finish up */
    fclose(f_regions_data);    
}


void geoclaw_region_normalize_coordinates(fclaw_global_t *glob, 
                                         fclaw_block_t *block,
                                         int blockno, 
                                         fclaw_region_t *r,
                                         double *xlower, double *xupper, 
                                         double *ylower, double *yupper,
                                         double *zlower, double *zupper)
{
    /*  
       Map region to normalized coordinates in a global [0,1]x[0,1]  domain.

       Gauge coordinates (g->xc,g->yc) are whatever the user supplied above 

       Return normalized (xlower,xupper)x(ylower,yupper) coordinates for region.
    */

    fclaw_options_t *fclaw_opt = fclaw_get_options(glob);
    double ax,bx,ay,by;

    ax = fclaw_opt->ax;
    bx = fclaw_opt->bx;
    ay = fclaw_opt->ay;
    by = fclaw_opt->by;

    /* Map region to global [0,1]x[0,1] space */
    *xlower = (r->xlower - ax)/(bx-ax);
    *xupper = (r->xupper - ax)/(bx-ax);
    *ylower = (r->ylower - ay)/(by-ay);
    *yupper = (r->yupper - ay)/(by-ay);

    /* These are not used in GeoClaw */
    *zlower = 0;
    *zupper = 0;
}


/* This assumes that no mapping is used and that the region is 
   defined in coordinates relative to [ax,bx]x[ay,by].
   If mapped grids are used, then the patch intersection may be 
   more involved
*/
int geoclaw_patch_intersects_region_default(fclaw_global_t *glob,
                                            fclaw_patch_t *patch,
                                            int blockno, int patchno,
                                            fclaw_region_t *r,
                                            double t,
                                            int refine_flag)
{   
    int rmin,rmax,num,dim;
    double xlower_reg, xupper_reg;
    double ylower_reg, yupper_reg;
    double zlower_reg, zupper_reg;
    double t1, t2;
    fclaw_region_get_data(glob,r,&num,&dim,
                          &xlower_reg, &xupper_reg, 
                          &ylower_reg, &yupper_reg, 
                          &zlower_reg, &zupper_reg, 
                          &rmin, &rmax,
                          &t1, &t2);

    /* Do a quick check */
    if (t < t1 || t > t2)        
        return 0;

    // Time is in time interval;  now check geometric intervals
    int mx,my,mbc;
    double xlower,ylower,dx,dy;
    double xupper, yupper;
    if (refine_flag != 0)
    {
        // We are refining and only passed in a single patch
        fclaw_clawpatch_2d_grid_data(glob,patch,&mx,&my,&mbc,
                                     &xlower,&ylower,&dx,&dy);
        xupper = xlower + mx*dx;
        yupper = ylower + my*dy;
    }
    else
    {
        /* We are passed in a family of four or eight patches
           for possible coarsening.
          
            ---------
            | 2 | 3 |   // Get xlower from patch 2
            ---------
            | 0 | 1 |   // Get ylower from patch 1
            ---------
        */
        double xlower1;  // Don't use this
        fclaw_clawpatch_2d_grid_data(glob,&patch[1],&mx,&my,&mbc,
                                     &xlower1,&ylower,&dx,&dy);
        xupper = xlower1 + mx*dx;

        // xlower unchanged on this call. 
        double ylower2;
        fclaw_clawpatch_2d_grid_data(glob,&patch[2],&mx,&my,&mbc,
                                     &xlower,&ylower2,&dx,&dy);
        yupper = ylower2 + my*dy;

    }

    if (xlower > xupper_reg || xupper < xlower_reg)
        return 0;

    if (ylower > yupper_reg || yupper < ylower_reg)
        return 0;

    return 1;
}

#ifdef __cplusplus
}
#endif

